language: cpp

compiler:
  - gcc
  - clang

os:
  - linux

configuration:
  - Release

matrix:
   fast_finish: true

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
      - kalakris-cmake

    packages:
      - clang-3.7
      - g++-6
      - gcc-6

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/cmake

git:
  submodules: true
  depth: 3

before_install:
  - git pull --recurse-submodules

install:
  - if [[ -n "$CLANG_VERSION" ]]; then export CXX=clang++-$CLANG_VERSION CC=clang-$CLANG_VERSION; fi
  - if [[ -n "$GCC_VERSION" ]]; then export CXX=g++-$GCC_VERSION CC=gcc-$GCC_VERSION; fi
  #- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

  # create directory to install dependencies (cmake, gcc etc)
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"

  # number of parallel jobs to run
  - JOBS=2

  # install more recent cmake version
  - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        if [[ -z "$(ls -A ${DEPS_DIR}/cmake/bin)" ]]; then
          CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz"
          mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
        fi
        export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
      else
        if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
      fi

before_script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
  - cd "${TRAVIS_BUILD_DIR}"
  - gcc -v && g++ -v && cmake --version
  - git pull --recurse-submodules

script:
  # set up out-of-source build folder
  - rm -rf ./build || true
  - mkdir ./build
  - cd build

  # configure
  - cmake ..

  # build
  - cmake --build . --clean-first

  # run automated tests
  - ctest -R all_tests --output-on-failure

notifications:
  email: false

sudo: required
