os: Visual Studio 2015

environment:
  matrix:
  - Toolset: mingw64
  - Toolset: v140
  - Toolset: v120

platform:
  - Win32
  - x64

configuration:
  - Release

matrix:
  allow_failures:
    - Toolset: v100
      platform: x64

build:
  verbosity: minimal

before_build:
  - ps: |
      git submodule update --init --recursive
      Write-Output "Configuration: $env:CONFIGURATION"
      Write-Output "Platform: $env:PLATFORM"

      $generator = switch ($env:TOOLSET)
      {
          "mingw64" { "MSYS Makefiles" }
          "v140" {"Visual Studio 14 2015"}
          "v120" {"Visual Studio 12 2013"}
          "v110" {"Visual Studio 11 2012"}
          "v100" {"Visual Studio 10 2010"}
      }

      if ($env:TOOLSET -eq "mingw64") {
          $env:PATH="C:\msys64\mingw64\bin;C:\msys64\usr\bin;$env:PATH"
      }
      elseif ($env:PLATFORM -eq "x64") {
          $generator = "$generator Win64"
      }

build_script:
  - ps: |
      md build -Force | Out-Null
      cd build
      if ($env:TOOLSET -eq "mingw64") {
          & cmake -G "$generator" -DCMAKE_BUILD_TYPE=$env:CONFIGURATION ..
      }
      else {
          & cmake -G "$generator" -DCMAKE_CONFIGURATION_TYPES="Debug;Release" ..
      }
      if ($LastExitCode -ne 0) {
          tree /f
          throw "Exception: $ErrorMessage"
      }

      & cmake --build . --config $env:CONFIGURATION

      if ($LastExitCode -ne 0) {
          tree /f
          throw "Exception: $ErrorMessage"
      }

test_script:
  - ps: |
      ctest -C $env:CONFIGURATION
      if ($LastExitCode -ne 0) {
          tree /f
          throw "Exception: $ErrorMessage"
      }
